import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NavbarPage from "@/components/NavbarPage";
import FooterPage from "@/components/FooterPage";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers attribute="class"
          defaultTheme="system"
          enableSystem>
             <NavbarPage/>
        {/* <main>{children}</main> */}
       
        
          {children}
          <FooterPage/>

  <Toaster />
        </Providers>
      </body>
    </html>
  );
}
